// Generated by CoffeeScript 1.10.0
var $, Game, ItemState, UpgradeState, a, add_commas, convert_save, format_number, product;

$ = document.getElementById.bind(document);

convert_save = function(fs) {
  var i, l, n, r, upgrades;
  r = {
    c: fs.Cupcakes,
    i: {}
  };
  for (i = l = 0; l <= 7; i = ++l) {
    n = fs['Inventory' + i];
    if (n === 0) {
      continue;
    }
    upgrades = fs.Upgrades[i] ? fs.Upgrades[i].length : 0;
    r.i[i] = {
      n: n,
      u: upgrades
    };
  }
  return r;
};

product = function(list) {
  var el, l, len, o;
  o = 1;
  for (l = 0, len = list.length; l < len; l++) {
    el = list[l];
    o *= el;
  }
  return o;
};

a = ['K', 'M', 'B', 'T', 'QD', 'QN', 'SX'];

add_commas = function(s) {
  var a_, x;
  a_ = s.split('').reverse().join('');
  return ((function() {
    var l, len, ref, results;
    ref = a_.match(/.{1,3}/g);
    results = [];
    for (l = 0, len = ref.length; l < len; l++) {
      x = ref[l];
      results.push(x.split("").reverse().join(""));
    }
    return results;
  })()).reverse().join(',');
};

format_number = function(n) {
  var d, f, g;
  g = 0;
  d = n >= 10000;
  while (n >= 10000000) {
    g++;
    n /= 1000;
  }
  f = Math.round(n);
  if (d) {
    f = add_commas(f.toString());
  }
  return f + (g ? " " + a[g - 1] : '');
};

UpgradeState = (function() {
  function UpgradeState(item, n1) {
    this.item = item;
    this.n = n1;
    this.all = this.item.type.upgrades;
    this.active = this.all.slice(0, this.n);
  }

  UpgradeState.prototype.calc_o_factor = function() {
    var x;
    return product((function() {
      var l, len, ref, results;
      ref = this.active;
      results = [];
      for (l = 0, len = ref.length; l < len; l++) {
        x = ref[l];
        results.push(x.o_factor);
      }
      return results;
    }).call(this));
  };

  UpgradeState.prototype.calc_i_factor = function() {
    var x;
    return product((function() {
      var l, len, ref, results;
      ref = this.active;
      results = [];
      for (l = 0, len = ref.length; l < len; l++) {
        x = ref[l];
        results.push(x.i_factor);
      }
      return results;
    }).call(this));
  };

  UpgradeState.prototype.n_active = function() {
    return this.active.length;
  };

  UpgradeState.prototype.buy = function() {
    var next;
    next = this.all[this.n];
    if (this.item.game.cupcakes < next.price) {
      return false;
    }
    this.active.push(next);
    return this.n++;
  };

  return UpgradeState;

})();

ItemState = (function() {
  function ItemState(game1, type) {
    this.game = game1;
    this.type = items[type];
    if (this.type.interval === null) {
      this.update = function() {
        return 0;
      };
    }
    this.n_items = 0;
    this.upgrades = new UpgradeState(this, 0);
    this.ms_left = Infinity;
    this.create_dom();
  }

  ItemState.prototype.load = function(save) {
    this.upgrades = new UpgradeState(this, save.u);
    this.n_items = save.n;
    return this.ms_left = this.calc_interval();
  };

  ItemState.prototype.save = function() {
    if (this.n_items) {
      return {
        n: this.n_items,
        u: this.upgrades.n_active()
      };
    }
  };

  ItemState.prototype.calc_price = function() {
    var extra, pm, pmg;
    pm = this.type.price_mult;
    if (this.n_items < 10) {
      pm *= 1;
    } else if (this.n_items < 50) {
      pm *= 1.2;
    } else if (this.n_items < 100) {
      pm *= 1.4;
    } else if (this.n_items < 500) {
      pm *= 1.6;
    } else if (this.n_items < 1000) {
      pm *= 3.3;
    } else if (this.n_items < 6000) {
      pm *= 6.5;
    }
    pmg = this.type.margin_price;
    if (this.n_items > 400) {
      if (pmg === 1) {
        pmg = 50;
      }
      if (pmg === 5) {
        pmg = 75;
      }
    } else if (this.n_items > 500) {
      0;
    }
    extra = pmg * this.n_items * pm;
    return this.type.base_price + extra;
  };

  ItemState.prototype.calc_output = function() {
    return this.n_items * this.type.output * this.upgrades.calc_o_factor();
  };

  ItemState.prototype.calc_interval = function() {
    if (this.type.interval === null) {
      return Infinity;
    }
    return this.type.interval * this.upgrades.calc_i_factor() * 1000;
  };

  ItemState.prototype.buy = function(n) {
    if (n == null) {
      n = 1;
    }
    if (this.game.cupcakes < this.calc_price() * n) {
      return false;
    }
    this.game.cupcakes -= this.calc_price() * n;
    this.n_items += n;
    this.game.interrupt_tick();
    return true;
  };

  ItemState.prototype.update = function(elapsed) {
    this.ms_left -= elapsed;
    if (this.ms_left <= 0) {
      this.ms_left += this.calc_interval();
      return this.calc_output();
    }
    return 0;
  };

  ItemState.prototype.create_dom = function() {
    var dom;
    dom = $('storetemplate').children[0].cloneNode(true);
    dom.getElementsByTagName('img')[0].src = "images/items/" + this.type.img;
    dom.getElementsByClassName('storename')[0].textContent = this.type.name;
    dom.getElementsByTagName('button')[0].addEventListener('click', (function(_this) {
      return function() {
        _this.buy();
        return _this.update_dom();
      };
    })(this));
    this.dom = dom;
    return this.update_dom();
  };

  ItemState.prototype.update_dom = function() {
    var e;
    this.dom.getElementsByClassName('storenumber')[0].textContent = this.n_items;
    this.dom.getElementsByTagName('button')[0].textContent = "Buy (" + (this.calc_price()) + ")";
    e = this.dom.getElementsByTagName('progress')[0];
    if (this.calc_interval() !== Infinity) {
      return e.max = this.calc_interval();
    } else {
      return e.style.display = "none";
    }
  };

  ItemState.prototype.hide = function() {
    return this.dom.parentElement.removeChild(this.dom);
  };

  ItemState.prototype.show = function() {
    return $('inventory').appendChild(this.dom);
  };

  return ItemState;

})();

Game = (function() {
  function Game() {
    var scope;
    this.items = {};
    this.cupcakes = 0;
    this.cc = $('cimage');
    this.cn = $('cupcake_number');
    this.cc.addEventListener('click', this.click.bind(this));
    this.load({
      c: 0,
      i: {}
    });
    this.last_tick = void 0;
    this.last_interval = void 0;
    this.picker = $('savepicker');
    scope = this;
    this.picker.addEventListener('change', function() {
      var blob, fileReader;
      if (scope.picker.files[0] != null) {
        blob = scope.picker.files[0];
        fileReader = new FileReader();
        fileReader.addEventListener('load', function() {
          var buf, u8a;
          scope.picker.value = '';
          buf = this.result;
          u8a = new Uint8Array(buf);
          scope.load(convert_save(decodeLSO(u8a)));
          return console.log('Loaded ccSave.sol');
        });
        return fileReader.readAsArrayBuffer(blob);
      }
    });
    this.loop(0);
  }

  Game.prototype.click = function() {
    this.cupcakes += this.items.helpers.calc_output() + 1;
    return this.interrupt_tick();
  };

  Game.prototype.tick = function(elapsed) {
    var _, i, x;
    x = (function() {
      var ref, results;
      ref = this.items;
      results = [];
      for (_ in ref) {
        i = ref[_];
        this.cupcakes += i.update(elapsed);
        results.push(i.ms_left);
      }
      return results;
    }).call(this);
    this.cn.textContent = (format_number(this.cupcakes)) + " Cupcakes";
    return Math.min.apply(Math, x);
  };

  Game.prototype.loop = function(elapsed) {
    var t;
    t = this.tick(elapsed);
    this.last_tick = window.performance.now();
    if (t !== Infinity) {
      return this.last_interval = setTimeout(((function(_this) {
        return function() {
          return _this.loop(t);
        };
      })(this)), t);
    }
  };

  Game.prototype.interrupt_tick = function() {
    clearTimeout(this.last_interval);
    return this.loop(window.performance.now() - this.last_tick);
  };

  Game.prototype.load = function(save) {
    var i, l, len, v;
    clearTimeout(this.last_interval);
    this.cupcakes = save.c;
    for (i = l = 0, len = order.length; l < len; i = ++l) {
      v = order[i];
      this.items[v] = new ItemState(this, v);
      if (save.i[i] != null) {
        this.items[v].load(save.i[i]);
      }
    }
    this.loop(0);
  };

  Game.prototype.save = function() {
    var k, o, ref, t, v;
    o = {
      c: this.cupcakes,
      i: {}
    };
    ref = this.items;
    for (k in ref) {
      v = ref[k];
      t = v.save();
      if (t) {
        o.i[v.type.idx] = t;
      }
    }
    return o;
  };

  Game.prototype.browser_save = function() {
    return localStorage.setItem('ccSave', JSON.stringify(this.save()));
  };

  Game.prototype.browser_load = function() {
    if (!localStorage.getItem('ccSave')) {
      return false;
    }
    game.load(JSON.parse(localStorage.getItem('ccSave')));
    return true;
  };

  Game.prototype.prompt_load = function() {
    return $('savepicker').click();
  };

  return Game;

})();

document.addEventListener('DOMContentLoaded', function() {
  var ch, fn, i, l, len, q, toggles, x;
  window.game = new Game();
  game.browser_load();
  ch = $('tabs').children;
  toggles = (function() {
    var l, len, results;
    results = [];
    for (l = 0, len = ch.length; l < len; l++) {
      x = ch[l];
      results.push($(x.getAttribute('data-toggle')));
    }
    return results;
  })();
  fn = function(q, i) {
    return i.addEventListener('click', function() {
      var j, len1, len2, m, p;
      for (m = 0, len1 = toggles.length; m < len1; m++) {
        j = toggles[m];
        if (j !== q) {
          j.style.display = "none";
        }
      }
      q.style.display = "";
      for (p = 0, len2 = ch.length; p < len2; p++) {
        j = ch[p];
        if (j !== i) {
          j.classList.remove('active');
        }
      }
      return i.classList.add('active');
    });
  };
  for (l = 0, len = ch.length; l < len; l++) {
    i = ch[l];
    q = $(i.getAttribute('data-toggle'));
    fn(q, i);
    continue;
  }
  window.addEventListener('beforeunload', function() {
    return game.browser_save();
  });
  setInterval((function() {
    return game.browser_save();
  }), 30000);
});
